#!/usr/bin/env bash
# Display Best School and Hi on iteration 9
count=1
while [ "$count" -le 10 ]
do
    echo "Best School"
    if [ "$count" -eq 9 ]
    then
        echo "Hi"
    fi
    count=$((count + 1))
done
