#!/bin/bash
python3 -c "a='bestchol';w=int(''.join(str('water'.index(c))for c in '$WATER'),5);s=int(''.join(str('stir.'.index(c))for c in '$STIR'),5);n=w+s;r=a[0]if not n else'';exec('while n:\n r=a[n%8]+r\n n//=8');print(r)"
